import { api } from '@/lib/api';
import type { MetricSnapshot } from '@/types/metrics';

/**
 * MetricsService
 *
 * Fetches GitHub activity snapshots for a developer.
 * Snapshots are generated by the backend Metrics Engine after each GitHub sync.
 *
 * Endpoint: GET /developers/:developerId/metrics
 * Response: MetricSnapshot[] ordered by periodStart DESC
 */
export const metricsService = {
  getByDeveloper: (developerId: string): Promise<MetricSnapshot[]> =>
    api.get<MetricSnapshot[]>(`/developers/${developerId}/metrics`),
};
